### ISSUE TITLE
Module/Setting to turn off GC for wrecks

### ISSUE THREAD

**Issue by Winter259** [kami-/hull#18]
For missions where wrecks are used for objectives/immersion (example: retrieve data from C130J wreck). I thought of a module so its just one click easy turn off.

**Comment by kami-** [comment]
`_object setVariable ["hull_gc_canRemove", false]` will disable GC on the given object. GC shouldn't be turned off unless you have a really good reason.

**Comment by Cyruz143** [comment]
Documented - can close
https://github.com/kami-/hull/wiki/Garbage-Collector
